def manage_errors(exception):
    print(f'Error: {exception}')
    