
def manage_error(exception):
    print(f'Error: {exception}')