
def manage_exceptions(exception):
    print(f'Error {exception}')